source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Notify_Example', :exclusive => true do
  pod 'Notify', :path => '../'
end

target 'Notify_Tests', :exclusive => true do
  pod 'Notify', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
